# ----------------------------------------------------------------------------
#
# Package             : ipywidgets
# Source Repo         : https://github.com/jupyter-widgets/ipywidgets.git
# Travis Job Link     : https://travis-ci.com/github/dthadi3/ipywidgets/builds/223543171
# Created travis.yml  : Yes
# Maintainer          : Devendranath Thadi <devendranath.thadi3@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
#https://travis-ci.org/github/jupyter-widgets/ipywidgets
arch:
  - amd64
  - ppc64le
language: python
dist: xenial
python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9
addons:
  apt_packages:
    - pandoc
  firefox: latest
services:
  - xvfb
cache: yarn
env:
    - GROUP=python
sudo: false
before_install:
    - 'if [[ $GROUP == python || doc ]] ; then pip install --upgrade setuptools pip; fi'
    - 'if [[ $GROUP == js ]] ; then nvm install 12 ; npm install --global yarn ; fi'
install:
    - 'if [[ $GROUP == python || doc ]] ; then pip install file://$PWD#egg=ipywidgets[test] coveralls; fi'
    - 'if [[ $GROUP == js ]] ; then echo `yarn -v` ; echo `node -v` ; yarn ; yarn run build ; yarn run build:examples ; fi'
script:
    - 'if [[ $GROUP == python ]] ; then pytest --cov=ipywidgets ipywidgets ; fi'
    - 'if [[ $GROUP == doc ]] ; then 
        pushd docs ;
        pip install -r requirements.txt ;
        make html ;
        popd ; fi'
    - 'if [[ $GROUP == js ]] ; then 
        export CHROME_BIN=chromium-browser ;
        yarn run integrity ;
        cd packages ;
        cd base ;
        yarn run test:unit:$BROWSER ;
        cd .. ;
        cd controls ;
        yarn run test:unit:$BROWSER ;
        cd .. ;
        cd html-manager ;
        yarn run test:unit:$BROWSER ;
        cd ../.. ;
        cd examples/web1 ;
        yarn run test:firefox ;
        cd ../.. ; fi'
matrix:
    include:
        - python: 3.6
          env: GROUP=doc
        - python: 3.6
          env: GROUP=doc
          arch: ppc64le
        - python: 3.6
          env: GROUP=js BROWSER=firefox
        - python: 3.6
          arch: ppc64le
          env: GROUP=js BROWSER=firefox
after_success:
    - coveralls
