# ----------------------------------------------------------------------------
#
# Package             : velero
# Source Repo         : https://github.com/konveyor/velero.git
# Travis Job Link     : https://travis-ci.com/github/dthadi3/velero/builds/216953757
# Created travis.yml  : Yes
# Maintainer          : Devendranath Thadi <devendranath.thadi3@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: go
os: linux
arch:
  - amd64
  - ppc64le
go:
  - 1.15
  - 1.14
